In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
data = pd.read_csv(r'C:\Users\ashis\OneDrive\Documents\Internship\Code Alpha Interndhip\ML Projects\archive\cs-training.csv')
data.head()

,Unnamed: 0,SeriousDlqin2yrs,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents
0,1,1,0.766127,45,2,0.802982,9120.0,13,0,6,0,2.0
1,2,0,0.957151,40,0,0.121876,2600.0,4,0,0,0,1.0
2,3,0,0.658180,38,1,0.085113,3042.0,2,1,0,0,0.0
3,4,0,0.233810,30,0,0.036050,3300.0,5,0,0,0,0.0
4,5,0,0.907239,49,1,0.024926,63588.0,7,0,1,0,0.0

In [3]:
data.shape

(150000, 12)

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 12 columns):
 #   Column                                Non-Null Count   Dtype
---  ------                                --------------   -----
 0   Unnamed: 0                            150000 non-null  int64
 1   SeriousDlqin2yrs                      150000 non-null  int64
 2   RevolvingUtilizationOfUnsecuredLines  150000 non-null  float64
 3   age                                   150000 non-null  int64
 4   NumberOfTime30-59DaysPastDueNotWorse  150000 non-null  int64
 5   DebtRatio                             150000 non-null  float64
 6   MonthlyIncome                         120269 non-null  float64
 7   NumberOfOpenCreditLinesAndLoans       150000 non-null  int64
 8   NumberOfTimes90DaysLate               150000 non-null  int64
 9   NumberRealEstateLoansOrLines          150000 non-null  int64
 10  NumberOfTime60-89DaysPastDueNotWorse  150000 non-null  int64
 11  NumberOfDependents                    146076 non-null  float64
dtypes: float64(4), int64(8)
memory usage: 13.7 MB

In [5]:
data.describe()

,Unnamed: 0,SeriousDlqin2yrs,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents
count,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000,1.202690e+05,150000.000000,150000.000000,150000.000000,150000.000000,146076.000000
mean,75000.500000,0.066840,6.048438,52.295207,0.421033,353.005076,6.670221e+03,8.452760,0.265973,1.018240,0.240387,0.757222
std,43301.414527,0.249746,249.755371,14.771866,4.192781,2037.818523,1.438467e+04,5.145951,4.169304,1.129771,4.155179,1.115086
min,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000
25%,37500.750000,0.000000,0.029867,41.000000,0.000000,0.175074,3.400000e+03,5.000000,0.000000,0.000000,0.000000,0.000000
50%,75000.500000,0.000000,0.154181,52.000000,0.000000,0.366508,5.400000e+03,8.000000,0.000000,1.000000,0.000000,0.000000
75%,112500.250000,0.000000,0.559046,63.000000,0.000000,0.868254,8.249000e+03,11.000000,0.000000,2.000000,0.000000,1.000000
max,150000.000000,1.000000,50708.000000,109.000000,98.000000,329664.000000,3.008750e+06,58.000000,98.000000,54.000000,98.000000,20.000000

In [6]:
data.isnull().sum()

Unnamed: 0                                  0
SeriousDlqin2yrs                            0
RevolvingUtilizationOfUnsecuredLines        0
age                                         0
NumberOfTime30-59DaysPastDueNotWorse        0
DebtRatio                                   0
MonthlyIncome                           29731
NumberOfOpenCreditLinesAndLoans             0
NumberOfTimes90DaysLate                     0
NumberRealEstateLoansOrLines                0
NumberOfTime60-89DaysPastDueNotWorse        0
NumberOfDependents                       3924
dtype: int64

In [7]:
data['MonthlyIncome'].fillna(data['MonthlyIncome'].median(), inplace=True)
data['NumberOfDependents'].fillna(data['NumberOfDependents'].median(), inplace=True)

C:\Users\ashis\AppData\Local\Temp\ipykernel_28592\1791568113.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['MonthlyIncome'].fillna(data['MonthlyIncome'].median(), inplace=True)
C:\Users\ashis\AppData\Local\Temp\ipykernel_28592\1791568113.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['NumberOfDependents'].fillna(data['NumberOfDependents'].median(), inplace=True)

In [8]:
data.drop(columns=['Unnamed: 0'], inplace=True)

In [9]:
data['LatePaymentRatio'] = (data['NumberOfTime30-59DaysPastDueNotWorse']+data['NumberOfTimes90DaysLate']+data['NumberOfTime60-89DaysPastDueNotWorse'])

In [11]:
X=data.drop('SeriousDlqin2yrs', axis=1)
y=data['SeriousDlqin2yrs']

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

In [13]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [16]:
from sklearn.linear_model import LogisticRegression
log_model=LogisticRegression()
log_model.fit(X_train, y_train)

LogisticRegression()

In [17]:
from sklearn.metrics import classification_report,roc_auc_score,accuracy_score,precision_score,recall_score,f1_score

In [18]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

In [19]:
dt=DecisionTreeClassifier(max_depth=5, random_state=42)
dt.fit(X_train, y_train)

DecisionTreeClassifier(max_depth=5, random_state=42)

In [20]:
rf=RandomForestClassifier(n_estimators=100, random_state=42)
rf.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [21]:
models={
    'Logistic Regression':log_model,
    'Decision Tree':dt,
    'Random Forest':rf
}

In [22]:
for name, model in models.items():
    y_pred=model.predict(X_test)
    roc=roc_auc_score(y_test, model.predict_proba(X_test)[:,1])
    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred)
    recall = recall_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)
    classification = classification_report(y_test, y_pred)

    print(name,"ROC-AOC:-",roc)
    print("Accuracy:", accuracy)
    print("Precision:", precision)
    print("Recall:", recall)
    print("F1 Score:", f1)
    print("Classification Report:\n", classification)

Logistic Regression ROC-AOC:- 0.7143523224444692
Accuracy: 0.934
Precision: 0.5806451612903226
Recall: 0.04488778054862843
F1 Score: 0.08333333333333333
Classification Report:
               precision    recall  f1-score   support

           0       0.94      1.00      0.97     27995
           1       0.58      0.04      0.08      2005

    accuracy                           0.93     30000
   macro avg       0.76      0.52      0.52     30000
weighted avg       0.91      0.93      0.91     30000

Decision Tree ROC-AOC:- 0.8481670266199122
Accuracy: 0.9365333333333333
Precision: 0.5996055226824457
Recall: 0.15162094763092268
F1 Score: 0.24203821656050956
Classification Report:
               precision    recall  f1-score   support

           0       0.94      0.99      0.97     27995
           1       0.60      0.15      0.24      2005

    accuracy                           0.94     30000
   macro avg       0.77      0.57      0.60     30000
weighted avg       0.92      0.94      0.92     30000

Random Forest ROC-AOC:- 0.838830170510498
Accuracy: 0.9361666666666667
Precision: 0.5675675675675675
Recall: 0.1885286783042394
F1 Score: 0.2830400599026582
Classification Report:
               precision    recall  f1-score   support

           0       0.94      0.99      0.97     27995
           1       0.57      0.19      0.28      2005

    accuracy                           0.94     30000
   macro avg       0.76      0.59      0.62     30000
weighted avg       0.92      0.94      0.92     30000

In [23]:
from sklearn.pipeline import Pipeline
import joblib

In [24]:
pipeline=Pipeline(steps=[('scaler', StandardScaler()), ('model', RandomForestClassifier(n_estimators=100, random_state=42, class_weight='balanced'))])
pipeline.fit(X_train, y_train)

Pipeline(steps=[('scaler', StandardScaler()),
                ('model',
                 RandomForestClassifier(class_weight='balanced',
                                        random_state=42))])

In [27]:
y_pred=pipeline.predict(X_test)
y_prob=pipeline.predict_proba(X_test)[:,1]

roc=roc_auc_score(y_test, y_prob)
print("Pipeline ROC-AUC:", roc)
recall=recall_score(y_test, y_pred)
f1=f1_score(y_test, y_pred)
print("Pipeline F1-score:", f1)
print("Pipeline Recall Score:", recall)

Pipeline ROC-AUC: 0.8372547021444424
Pipeline F1-score: 0.24765625
Pipeline Recall Score: 0.15810473815461346

In [28]:
joblib.dump(pipeline, 'credit_score_model.joblib')

['credit_score_model.joblib']

In [29]:
loaded_model=joblib.load('credit_score_model.joblib')

In [30]:
test_data = pd.DataFrame({
    "RevolvingUtilizationOfUnsecuredLines": [0.45, 0.90, 0.15],
    "age": [45, 30, 60],
    "NumberOfTime30-59DaysPastDueNotWorse": [1, 4, 0],
    "DebtRatio": [0.35, 0.85, 0.20],
    "MonthlyIncome": [5000, 3000, 8000],
    "NumberOfOpenCreditLinesAndLoans": [8, 5, 10],
    "NumberOfTimes90DaysLate": [0, 2, 0],
    "NumberRealEstateLoansOrLines": [1, 0, 2],
    "NumberOfTime60-89DaysPastDueNotWorse": [0, 1, 0],
    "NumberOfDependents": [2, 1, 0],
    "LatePaymentRatio": [1, 7, 0]
})

In [ ]:
def credit_decision(probablity):
    if probablity>=0.4:
        return "Reject"
    elif probablity>=0.25:
        return "Manual Review"
    else:
        return "Approve"

test_data['Decision']=test_data['Probability']

In [40]:
loaded_model.named_steps["scaler"].n_features_in_

11

In [41]:
test_data.shape

(3, 13)

In [43]:
trained_features = X.columns
trained_features

Index(['RevolvingUtilizationOfUnsecuredLines', 'age',
       'NumberOfTime30-59DaysPastDueNotWorse', 'DebtRatio', 'MonthlyIncome',
       'NumberOfOpenCreditLinesAndLoans', 'NumberOfTimes90DaysLate',
       'NumberRealEstateLoansOrLines', 'NumberOfTime60-89DaysPastDueNotWorse',
       'NumberOfDependents', 'LatePaymentRatio'],
      dtype='object')

In [44]:
test_data_fixed= test_data[trained_features]

In [45]:
test_data_fixed.shape

(3, 11)

In [46]:
predictions = loaded_model.predict(test_data_fixed)
probabilities = loaded_model.predict_proba(test_data_fixed)[:, 1]

C:\Users\ashis\miniconda3\Lib\site-packages\sklearn\utils\validation.py:2732: UserWarning: X has feature names, but StandardScaler was fitted without feature names
  warnings.warn(
C:\Users\ashis\miniconda3\Lib\site-packages\sklearn\utils\validation.py:2732: UserWarning: X has feature names, but StandardScaler was fitted without feature names
  warnings.warn(

In [47]:
test_data['Prediction']=predictions
test_data['Probability']=probabilities

In [48]:
def credit_decision(probability):
    if probability>=0.4:
        return "Reject"
    elif probability>=0.25:
        return "Manual Review"
    else:
        return "Approve"

test_data['Decision']=test_data['Probability'].apply(credit_decision)

In [49]:
test_data

,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents,LatePaymentRatio,Prediction,Probability,Decision
0,0.45,45,1,0.35,5000,8,0,1,0,2,1,0,0.12,Approve
1,0.90,30,4,0.85,3000,5,2,0,1,1,7,0,0.38,Manual Review
2,0.15,60,0,0.20,8000,10,0,2,0,0,0,0,0.08,Approve